[package]
name = "rustnes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.13.0"

[dependencies.yaml-rust]
sdl2 = "0.35"